In [2]:
print("helloha")

helloha


In [1]:
import numpy as np

In [3]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [4]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [5]:
b.ndim

2

In [6]:
b.shape

(2, 3)

In [7]:
m = np.array([
    [ 1,  2,  3,  4,  5],
    [ 6,  7,  8,  9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25],
    [26, 27, 28, 29, 30]
])

In [8]:
m[2:4, 0:2]

array([[11, 12],
       [16, 17]])